music_directory     "/var/lib/mpd/music"
playlist_directory  "/var/lib/mpd/playlists"
db_file             "/var/lib/mpd/database"
state_file          "/var/lib/mpd/state"
sticker_file        "/var/lib/mpd/sticker.sql"

bind_to_address     "0.0.0.0"
port                "6600"

audio_output {
    type        "alsa"
    name        "Audio Amp SHIM"
    mixer_type  "software"
    channels    "1"
}
